export const mainMetrics = [
  {
    month_year: "2024-11-1",
    total_new_tasks: 14,
    total_finished_tasks: 7,
    current_in_progress_tasks: 5,
    current_pending_tasks: 4,
    current_completed_tasks: 4,
    user_satisfactions: 80,
  },
  {
    month_year: "2024-12-1",
    total_new_tasks: 18,
    total_finished_tasks: 8,
    current_in_progress_tasks: 7,
    current_pending_tasks: 8,
    current_completed_tasks: 10,
    user_satisfactions: 75.84,
  },
  {
    month_year: "2025-01-1",
    total_new_tasks: 4,
    total_finished_tasks: 8,
    current_in_progress_tasks: 7,
    current_pending_tasks: 8,
    current_completed_tasks: 10,
    user_satisfactions: 75.84,
  },
  {
    month_year: "2025-02-1",
    total_new_tasks: 11,
    total_finished_tasks: 8,
    current_in_progress_tasks: 7,
    current_pending_tasks: 8,
    current_completed_tasks: 10,
    user_satisfactions: 75.84,
  },
  {
    month_year: "2025-03-1",
    total_new_tasks: 24,
    total_finished_tasks: 8,
    current_in_progress_tasks: 7,
    current_pending_tasks: 8,
    current_completed_tasks: 10,
    user_satisfactions: 75.84,
  },
  {
    month_year: "2025-04-1",
    total_new_tasks: 12,
    total_finished_tasks: 8,
    current_in_progress_tasks: 7,
    current_pending_tasks: 8,
    current_completed_tasks: 10,
    user_satisfactions: 75.84,
  },
  {
    month_year: "2025-05-1",
    total_new_tasks: 61,
    total_finished_tasks: 8,
    current_in_progress_tasks: 7,
    current_pending_tasks: 8,
    current_completed_tasks: 10,
    user_satisfactions: 75.84,
  },
  {
    month_year: "2025-06-1",
    total_new_tasks: 16,
    total_finished_tasks: 8,
    current_in_progress_tasks: 7,
    current_pending_tasks: 8,
    current_completed_tasks: 10,
    user_satisfactions: 75.84,
  },
  {
    month_year: "2025-07-1",
    total_new_tasks: 4,
    total_finished_tasks: 8,
    current_in_progress_tasks: 7,
    current_pending_tasks: 8,
    current_completed_tasks: 10,
    user_satisfactions: 75.84,
  },
  {
    month_year: "2025-08-1",
    total_new_tasks: 12,
    total_finished_tasks: 8,
    current_in_progress_tasks: 7,
    current_pending_tasks: 8,
    current_completed_tasks: 10,
    user_satisfactions: 75.84,
  },
  {
    month_year: "2025-09-1",
    total_new_tasks: 16,
    total_finished_tasks: 8,
    current_in_progress_tasks: 7,
    current_pending_tasks: 8,
    current_completed_tasks: 10,
    user_satisfactions: 75.84,
  },
  {
    month_year: "2025-10-1",
    total_new_tasks: 15,
    total_finished_tasks: 22,
    current_in_progress_tasks: 12,
    current_pending_tasks: 5,
    current_completed_tasks: 12,
    user_satisfactions: 75.84,
  },
];

export const locationMetrics = [
  {
    location: "Location 1",
    total_tasks: 20,
    flag_color: "#faf95a",
    total_finished_tasks: 15,
  },
  {
    location: "Location 2",
    total_tasks: 14,
    flag_color: "#ffa95a",
    total_finished_tasks: 12,
  },
  {
    location: "Location 3",
    flag_color: "#f0f033",
    total_tasks: 20,
    total_finished_tasks: 15,
  },
];

export const categoryMetrics = [
  {
    category: "kebijakan-publik",
    total_tasks: 4,
    total_finished_tasks: 4,
  },
  {
    category: "kondisi-jalan",
    total_tasks: 10,
    total_finished_tasks: 8,
  },
  {
    category: "fasilitas-umum",
    total_tasks: 12,
    total_finished_tasks: 4,
  },
  {
    category: "makanan-bergizi",
    total_tasks: 5,
    total_finished_tasks: 1,
  },
  {
    category: "program-pemerintah",
    total_tasks: 7,
    total_finished_tasks: 5,
  },
  {
    category: "keamanan",
    total_tasks: 12,
    total_finished_tasks: 6,
  },
  {
    category: "pungli",
    total_tasks: 6,
    total_finished_tasks: 2,
  },
  {
    category: "lainnya",
    total_tasks: 10,
    total_finished_tasks: 6,
  },
];
