import { Report } from "@/types/report.types";

export const reports = [
  {
    id: "3b5fac14-083c-11f0-b077-37b843d1bcb3",
    tracking_id: "ABC88BB44",
    title: "Jalan Rusak Berat",
    description: "Kondisi jalan yang rusak di beberapa titik.",
    address: {
      full_address: "Jl. Raya No. 5, Jakarta",
      village: "Kec. Sukalaka",
      district: "Jakarta",
      lat: "12.3456",
      lng: "65.4321",
    },
    created_at: "2025-03-01T10:00:00Z",
    category: "kondisi-jalan",
    images: ["cdn.example.com/images/jalan1.jpg"],
    data: {
      follow_up_questions: [
        { q: "Apakah ada perbaikan?", a: "Belum ada" },
        { q: "Kapan jalan ini diperbaiki?", a: "Belum ada informasi" },
      ],
    },
    rating: 3,
    status: "COMPLETED",
    priority: "HIGH",
    progress: [
      {
        updated_by: "John Doe",
        status: "IN_PROGRESS",
        updated_at: "2025-03-01T10:00:00Z",
        message: "Laporan diterima",
        img: "cdn.example.com/images/update1.jpg",
      },
      {
        updated_by: "Jane Doe",
        status: "COMPLETED",
        updated_at: "2025-03-10T10:00:00Z",
        message: "Perbaikan selesai",
        img: "cdn.example.com/images/update2.jpg",
      },
    ],
  },
  {
    id: "2",
    tracking_id: "ABC88BB46",
    title: "Program Sosial Pemerintah",
    description: "Pembagian sembako oleh pemerintah.",
    address: {
      full_address: "Jl. Sembako No. 1, Surabaya",
      village: "Kec. Sukasuka",
      district: "Surabaya",
      lat: "12.3456",
      lng: "65.4321",
    },
    created_at: "2025-03-02T10:05:00Z",
    category: "program-pemerintah",
    images: ["cdn.example.com/images/jalan1.jpg"],
    status: "PENDING",
    priority: "MID",
    progress: null,
    rating: 0,
    data: null,
  },
  {
    id: "3",
    tracking_id: "ABC88BBX4",
    title: "Pungli di Pasar",
    description: "Ada praktik pungli di pasar tradisional.",
    address: {
      full_address: "Jl. Pungli No. 3, Surabaya",
      village: "Kec. Sukaminta",
      district: "Surabaya",
      lat: "12.3456",
      lng: "65.4321",
    },
    created_at: "2025-03-03T10:10:00Z",
    category: "pungli",
    rating: 0,
    images: ["cdn.example.com/images/jalan1.jpg"],
    data: {
      follow_up_questions: [
        { q: "Berapa jumlah pungli?", a: "Rp 20.000 per orang" },
      ],
    },
    status: "IN_PROGRESS",
    priority: "CRITICAL",
    progress: [
      {
        updated_by: "John Doe",
        status: "IN_PROGRESS",
        updated_at: "2025-03-03T10:10:00Z",
        message: "Laporan sedang diproses",
        img: "cdn.example.com/images/update3.jpg",
      },
    ],
  },
  {
    id: "4",
    tracking_id: "JF85BB44",
    title: "Kebijakan Publik Baru",
    description: "Pengenalan kebijakan publik terkait pendidikan.",
    created_at: "2025-03-04T10:15:00Z",
    address: {
      full_address: "",
      village: "",
      district: "",
      lat: "",
      lng: "",
    },
    category: "kebijakan-publik",
    images: ["cdn.example.com/images/jalan1.jpg"],
    status: "COMPLETED",
    rating: 9,
    priority: "MID",
    progress: [
      {
        updated_by: "Jane Doe",
        status: "IN_PROGRESS",
        updated_at: "2025-03-04T10:15:00Z",
        message: "Sedang dijalankan",
        img: "cdn.example.com/images/update4.jpg",
      },
      {
        updated_by: "John Doe",
        status: "COMPLETED",
        updated_at: "2025-03-05T10:20:00Z",
        message: "Kebijakan diterima masyarakat",
        img: "cdn.example.com/images/update5.jpg",
      },
    ],
    data: null,
  },
  {
    id: "5",
    tracking_id: "MM98BB44",
    title: "Keamanan Lingkungan",
    description: "Tingkat kejahatan meningkat di lingkungan ini.",
    address: {
      full_address: "Jl. Aman No. 7, Bandung",
      village: "Bandung Selatan",
      district: "Bandung",
      lat: "10.1234",
      lng: "50.6789",
    },
    created_at: "2025-03-06T10:25:00Z",
    category: "keamanan",
    images: ["cdn.example.com/images/jalan1.jpg"],
    status: "IN_PROGRESS",
    rating: 0,
    priority: "HIGH",
    progress: [
      {
        updated_by: "John Doe",
        status: "IN_PROGRESS",
        updated_at: "2025-03-06T10:25:00Z",
        message: "Masyarakat sudah waspada",
        img: "cdn.example.com/images/update6.jpg",
      },
    ],
    data: {
      follow_up_questions: [
        { q: "Apa tindakan yang diambil?", a: "Pemasangan CCTV" },
      ],
    },
  },
  {
    id: "6",
    tracking_id: "XOXO1212",
    title: "Fasilitas Umum",
    description: "Fasilitas umum seperti toilet rusak.",
    created_at: "2025-12-07T10:30:00Z",
    category: "fasilitas-umum",
    address: {
      full_address: "Jl. Toilets No. 6, Bandung",
      village: "",
      district: "Kec. Sukarusak",
      lat: "10.1234",
      lng: "50.6789",
    },
    images: ["cdn.example.com/images/jalan1.jpg"],
    status: "PENDING",
    priority: "LOW",
    progress: null,
    rating: 0,
    data: null,
  },
  {
    id: "7",
    tracking_id: "00JJBB88",
    title: "Program Kesehatan",
    description: "Bantuan kesehatan gratis di wilayah terpencil.",
    address: {
      full_address: "Jl. Kesehatan No. 3, Medan",
      village: "Medan Timur",
      district: "Medan",
      lat: "10.1234",
      lng: "50.6789",
    },
    created_at: "2025-10-08T10:35:00Z",
    category: "program-pemerintah",
    images: ["cdn.example.com/images/jalan1.jpg"],
    status: "COMPLETED",
    priority: "MID",
    rating: 0,
    progress: [
      {
        updated_by: "John Doe",
        status: "IN_PROGRESS",
        updated_at: "2025-08-08T10:35:00Z",
        message: "Sedang dilaksanakan",
        img: "cdn.example.com/images/update7.jpg",
      },
      {
        updated_by: "Jane Doe",
        status: "COMPLETED",
        updated_at: "2025-03-09T10:40:00Z",
        message: "Program selesai dengan sukses",
        img: "cdn.example.com/images/update8.jpg",
      },
    ],
    data: null,
  },
  {
    id: "8",
    tracking_id: "8B8I1212",
    title: "Laporan Sampah",
    description: "Tumpukan sampah yang tidak tertangani dengan baik.",
    address: {
      full_address: "",
      village: "Medan Timur",
      district: "Medan",
      lat: "10.1234",
      lng: "50.6789",
    },
    created_at: "2025-05-09T10:45:00Z",
    category: "lainnya",
    rating: 0,
    images: ["cdn.example.com/images/jalan1.jpg"],
    status: "IN_PROGRESS",
    priority: "HIGH",
    progress: [
      {
        updated_by: "John Doe",
        status: "IN_PROGRESS",
        updated_at: "2025-03-09T10:45:00Z",
        message: "Pembersihan sedang berlangsung",
        img: "cdn.example.com/images/update9.jpg",
      },
    ],
    data: null,
  },
  {
    id: "9",
    tracking_id: "XO90IJBB",
    title: "Makanan Bergizi",
    description: "Program makan bergizi di sekolah.",
    created_at: "2025-04-10T10:50:00Z",
    category: "makanan-bergizi",
    images: ["cdn.example.com/images/jalan1.jpg"],
    address: {
      full_address: "",
      village: "Medan Utara",
      district: "Medan",
      lat: "10.1234",
      lng: "50.6789",
    },
    status: "COMPLETED",
    rating: 8,
    priority: "MID",
    progress: [
      {
        updated_by: "Jane Doe",
        status: "IN_PROGRESS",
        updated_at: "2025-03-10T10:50:00Z",
        message: "Persiapan mulai",
        img: "cdn.example.com/images/update10.jpg",
      },
      {
        updated_by: "John Doe",
        status: "COMPLETED",
        updated_at: "2025-03-11T10:55:00Z",
        message: "Program selesai",
        img: "cdn.example.com/images/update11.jpg",
      },
    ],
    data: null,
  },
  {
    id: "10",
    tracking_id: "XO9JXJBB",
    title: "Tindak Kejahatan di Wilayah Ini",
    description: "Peningkatan kasus kejahatan di daerah ini.",
    created_at: "2025-03-11T10:55:00Z",
    category: "keamanan",
    address: {
      full_address: "Jl. Kejahatan No. 10, Medan Gotham City",
      village: "Gotham City",
      district: "Medan",
      lat: "10.1234",
      lng: "50.6789",
    },
    images: ["cdn.example.com/images/jalan1.jpg"],
    status: "IN_PROGRESS",
    rating: 0,
    priority: "CRITICAL",
    progress: [
      {
        updated_by: "John Doe",
        status: "IN_PROGRESS",
        updated_at: "2025-03-11T10:55:00Z",
        message: "Penyelidikan sedang berlangsung",
        img: "cdn.example.com/images/update12.jpg",
      },
    ],
    data: null,
  },
  {
    id: "11",
    tracking_id: "XOFIXJBB",
    title: "Renovasi Taman Kota",
    description: "Renovasi taman kota yang mulai tidak terawat.",
    address: {
      full_address: "Jl. Taman No. 11, Jogja",
      village: "Pandean",
      district: "Jogja",
      lat: "10.1234",
      lng: "50.6789",
    },
    created_at: "2025-03-12T10:00:00Z",
    category: "fasilitas-umum",
    images: ["cdn.example.com/images/jalan1.jpg"],
    status: "IN_PROGRESS",
    priority: "MID",
    rating: 5,
    progress: [
      {
        updated_by: "John Doe",
        status: "IN_PROGRESS",
        updated_at: "2025-03-12T10:00:00Z",
        message: "Proyek dimulai",
        img: "cdn.example.com/images/update1.jpg",
      },
      {
        updated_by: "Jane Doe",
        status: "IN_PROGRESS",
        updated_at: "2025-03-13T10:05:00Z",
        message: "Progres pengerjaan taman",
        img: "cdn.example.com/images/update2.jpg",
      },
      {
        updated_by: "Alice Smith",
        status: "IN_PROGRESS",
        updated_at: "2025-03-14T10:10:00Z",
        message: "Pengadaan material selesai",
        img: "cdn.example.com/images/update3.jpg",
      },
      {
        updated_by: "Bob Johnson",
        status: "IN_PROGRESS",
        updated_at: "2025-03-15T10:15:00Z",
        message: "Pekerjaan fisik berlangsung",
        img: "cdn.example.com/images/update4.jpg",
      },
      {
        updated_by: "Jane Doe",
        status: "COMPLETED",
        updated_at: "2025-03-16T10:20:00Z",
        message: "Renovasi taman selesai",
        img: "cdn.example.com/images/update5.jpg",
      },
    ],
    data: null,
  },
  {
    id: "12",
    tracking_id: "XOXO5212",
    title: "Kebijakan Pendidikan Baru",
    description: "Implementasi kebijakan baru dalam dunia pendidikan.",
    created_at: "2025-03-13T10:05:00Z",
    category: "kebijakan-publik",
    address: {
      full_address: "Jl. Pendidikan No. 12, Jogja",
      village: "Tamsis",
      district: "Jogja",
      lat: "10.1234",
      lng: "50.6789",
    },
    images: ["cdn.example.com/images/jalan1.jpg"],
    status: "PENDING",
    priority: "HIGH",
    rating: 0,
    progress: null,
    data: null,
  },
  {
    id: "13",
    title: "Masalah Lalu Lintas",
    description: "Kemacetan yang semakin parah di beberapa titik kota.",
    address: {
      full_address: "Jl. Lalu Lintas No. 13, Jogja",
      village: "Jogja",
      district: "Jogja",
      lat: "10.1234",
      lng: "50.6789",
    },
    created_at: "2025-03-14T10:10:00Z",
    category: "kondisi-jalan",
    images: ["cdn.example.com/images/jalan1.jpg"],
    status: "IN_PROGRESS",
    priority: "CRITICAL",
    rating: 7,
    progress: [
      {
        updated_by: "John Doe",
        status: "IN_PROGRESS",
        updated_at: "2025-03-14T10:10:00Z",
        message: "Kemacetan parah terpantau",
        img: "cdn.example.com/images/update1.jpg",
      },
      {
        updated_by: "Alice Smith",
        status: "IN_PROGRESS",
        updated_at: "2025-03-15T10:15:00Z",
        message: "Analisis jalan sedang dilakukan",
        img: "cdn.example.com/images/update2.jpg",
      },
      {
        updated_by: "Bob Johnson",
        status: "IN_PROGRESS",
        updated_at: "2025-03-16T10:20:00Z",
        message: "Perencanaan solusi dimulai",
        img: "cdn.example.com/images/update3.jpg",
      },
      {
        updated_by: "Jane Doe",
        status: "IN_PROGRESS",
        updated_at: "2025-03-17T10:25:00Z",
        message: "Pengajuan anggaran untuk solusi",
        img: "cdn.example.com/images/update4.jpg",
      },
      {
        updated_by: "John Doe",
        status: "COMPLETED",
        updated_at: "2025-03-18T10:30:00Z",
        message: "Solusi diterapkan",
        img: "cdn.example.com/images/update5.jpg",
      },
    ],
    data: {
      follow_up_questions: [
        {
          q: "Apa solusi untuk kemacetan?",
          a: "Pemasangan lampu lalu lintas baru",
        },
        { q: "Kapan implementasi solusi?", a: "2 minggu dari sekarang" },
      ],
    },
  },
  {
    id: "14",
    tracking_id: "XDJO5212",
    title: "Penyalahgunaan Dana Publik",
    description: "Terdapat dugaan penyalahgunaan dana dalam proyek publik.",
    created_at: "2025-03-15T10:15:00Z",
    category: "pungli",
    images: ["cdn.example.com/images/jalan1.jpg"],
    status: "PENDING",
    address: {
      full_address: "Jl. Pungli No. 14, Jogja",
      village: "Desa Sukapungli",
      district: "Jogja",
      lat: "10.1234",
      lng: "50.6789",
    },
    priority: "HIGH",
    rating: 0,
    progress: null,
    data: null,
  },
  {
    id: "15",
    tracking_id: "XFJO5212",
    title: "Fasilitas Kesehatan Terbatas",
    description: "Fasilitas kesehatan di daerah ini sangat terbatas.",
    address: {
      full_address: "Jl. Sehat No. 3, Bali",
      village: "Kuta Bali",
      district: "Bali",
      lat: "10.1234",
      lng: "50.6789",
    },
    created_at: "2025-03-16T10:20:00Z",
    category: "fasilitas-umum",
    images: ["cdn.example.com/images/jalan1.jpg"],
    status: "IN_PROGRESS",
    priority: "MID",
    rating: 3,
    progress: [
      {
        updated_by: "John Doe",
        status: "IN_PROGRESS",
        updated_at: "2025-03-16T10:20:00Z",
        message: "Fasilitas yang rusak mulai diperbaiki",
        img: "cdn.example.com/images/update1.jpg",
      },
      {
        updated_by: "Jane Doe",
        status: "IN_PROGRESS",
        updated_at: "2025-03-17T10:25:00Z",
        message: "Pemeriksaan alat medis",
        img: "cdn.example.com/images/update2.jpg",
      },
      {
        updated_by: "Bob Johnson",
        status: "IN_PROGRESS",
        updated_at: "2025-03-18T10:30:00Z",
        message: "Pemasangan alat medis baru",
        img: "cdn.example.com/images/update3.jpg",
      },
      {
        updated_by: "Alice Smith",
        status: "IN_PROGRESS",
        updated_at: "2025-03-19T10:35:00Z",
        message: "Fasilitas mulai dapat digunakan",
        img: "cdn.example.com/images/update4.jpg",
      },
      {
        updated_by: "John Doe",
        status: "COMPLETED",
        updated_at: "2025-03-20T10:40:00Z",
        message: "Perbaikan selesai dan berfungsi dengan baik",
        img: "cdn.example.com/images/update5.jpg",
      },
    ],
    data: null,
  },
  {
    id: "16",
    tracking_id: "XJJO5212",
    title: "Pendidikan Anak Usia Dini",
    description:
      "Ketersediaan fasilitas pendidikan anak usia dini yang terbatas.",
    created_at: "2025-03-17T10:25:00Z",
    address: {
      full_address: "",
      lng: "",
      lat: "",
      village: "",
      district: "Gatau Dimana",
    },
    category: "program-pemerintah",
    images: ["cdn.example.com/images/jalan1.jpg"],
    status: "COMPLETED",
    priority: "LOW",
    rating: 8,
    progress: [
      {
        updated_by: "John Doe",
        status: "IN_PROGRESS",
        updated_at: "2025-03-17T10:25:00Z",
        message: "Proses pembangunan fasilitas dimulai",
        img: "cdn.example.com/images/update1.jpg",
      },
      {
        updated_by: "Jane Doe",
        status: "COMPLETED",
        updated_at: "2025-03-18T10:30:00Z",
        message: "Pendidikan anak usia dini mulai diberikan",
        img: "cdn.example.com/images/update2.jpg",
      },
    ],
    data: null,
  },
  {
    id: "17",
    tracking_id: "XBANJ1212",
    title:
      "Banjir di Wilayah X menyebabkan kerusakan besar. Coba dong pemerintah toloong",
    description: "Banjir yang melanda wilayah X menyebabkan kerusakan besar.",
    address: {
      full_address: "Jl. Banjir No. 9, Palembang",
      lng: "58.5678",
      lat: "15.1234",
      village: "Sukabandjir",
      district: "Palembang",
    },
    created_at: "2025-03-18T10:40:00Z",
    category: "lainnya",
    images: ["cdn.example.com/images/jalan1.jpg"],
    status: "IN_PROGRESS",
    priority: "CRITICAL",
    rating: 9,
    progress: [
      {
        updated_by: "Alice Smith",
        status: "IN_PROGRESS",
        updated_at: "2025-03-18T10:40:00Z",
        message: "Banjir mulai surut",
        img: "cdn.example.com/images/update1.jpg",
      },
      {
        updated_by: "John Doe",
        status: "IN_PROGRESS",
        updated_at: "2025-03-19T10:45:00Z",
        message: "Bantuan darurat diterima",
        img: "cdn.example.com/images/update2.jpg",
      },
      {
        updated_by: "Bob Johnson",
        status: "IN_PROGRESS",
        updated_at: "2025-03-20T10:50:00Z",
        message: "Evakuasi dilakukan",
        img: "cdn.example.com/images/update3.jpg",
      },
      {
        updated_by: "Alice Smith",
        status: "IN_PROGRESS",
        updated_at: "2025-03-21T10:55:00Z",
        message: "Pemulihan kawasan berlangsung",
        img: "cdn.example.com/images/update4.jpg",
      },
      {
        updated_by: "John Doe",
        status: "COMPLETED",
        updated_at: "2025-03-22T11:00:00Z",
        message: "Bantuan dan pemulihan selesai",
        img: "cdn.example.com/images/update5.jpg",
      },
    ],
    data: null,
  },
] as Report[];
